[project]
name = "ckanext-schema_field_groups"
version = "0.0.1"
description = "Field groups in schema"
readme = "README.md"
authors = [
    {name = "Derilinx", email = "dev@derilinx.com"}
]
license = {text = "AGPL"}
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

keywords = [ "CKAN", "scheming"]
dependencies = []

[project.urls]
Homepage = "https://github.com/derilinx/ckanext-schema_field_groups"

[project.entry-points."ckan.plugins"]
schema_field_groups = "ckanext.schema_field_groups.plugin:SchemaFieldGroupsPlugin"

[project.entry-points."babel.extractors"]
ckan = "ckan.lib.extract:extract_ckan"


[build-system]
requires = ["setuptools<82"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
        "ignore::sqlalchemy.exc.SADeprecationWarning",
        "ignore::sqlalchemy.exc.SAWarning",
        "ignore::DeprecationWarning",
]
addopts = "--ckan-ini test.ini"
